name: Run test on playback-testing

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      suites: 
        description: 'Test Suites, separated by commas (if empty, all will be ran)'
        default: ''
        required: false
      MUX-CDN-URL:
        description: 'MUX-CDN-URL'
        required: false

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Run test on playback-testing
        if: github.event.action != 'Tests results on playback-testing'
        run: |
          curl -X POST https://api.github.com/repos/muxinc/playback-testing/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "players": "mux", "drivers": "chrome", "suites": "'${{ github.event.inputs.suites }}'", "MUX-CDN-URL":"'${{ github.event.inputs.MUX-CDN-URL }}'"  }}'
      - name: Show test results of playback-testing
        if: github.event.action == 'Tests results on playback-testing'
        run: echo -e '${{toJSON(github.event.client_payload.data)}}'
