

name: testtt

on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Test Suites, separated by commas (if empty, all will be ran)'
        default: ''
        required: false
      MUX-CDN-URL:
        description: 'Mux Player hosted script'
        required: false

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Send Results
        run: |
          curl   -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: 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"   https://api.github.com/repos/hernanr99/elements/check-runs   -d '{"name":"mighty_readme","head_sha":"ce587453ced02b1526dfb4cb910479d431683101","status":"in_progress","external_id":"42","started_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report","summary":"","text":""}}'

