

name: testtt

on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Test Suites, separated by commas (if empty, all will be ran)'
        default: ''
        required: false
      MUX-CDN-URL:
        description: 'Mux Player hosted script'
        required: false

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Send Results
        if: github.event.action == 'Run integration tests'
        run: |
          curl -X GET https://api.github.com/repos/muxinc/playback-testing/check-runs/3331055970 \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Authorization: Bearer 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" \
          

