

name: testtt

on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Test Suites, separated by commas (if empty, all will be ran)'
        default: ''
        required: false
      MUX-CDN-URL:
        description: 'Mux Player hosted script'
        required: false

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method GET /repos/muxinc/playback-testing/actions/runs

